faq/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.faq, name='faq'),
]

ms4_england_cricket_tickets/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('tours/', include('tours.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('faq/', include('faq.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tours/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.tours, name='tours'),
    path('<int:match_id>/', views.tickets, name='tickets'),
    path('product_management/', views.product_management,
         name='product_management'),
    path('add_match/', views.add_match, name='add_match'),
    path('add_ticket/', views.add_ticket, name='add_ticket'),
    path('add_stadium/', views.add_stadium, name='add_stadium'),
    path('add_tour/', views.add_tour, name='add_tour'),
    path('edit_match/<int:match_id>/', views.edit_match, name='edit_match'),
    path('delete_match/<int:match_id>/', views.delete_match,
         name='delete_match'),
    path('edit_ticket/<int:ticket_id>/', views.edit_ticket,
         name='edit_ticket'),
    path('delete_ticket/<int:ticket_id>/', views.delete_ticket,
         name='delete_ticket'),
]

checkout/models.py
import uuid
from django.db import models
from django.db.models import Sum
from django.conf import settings
from django_countries.fields import CountryField
from tours.models import Ticket
from profiles.models import UserProfile


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True,
                                     related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(max_digits=6, decimal_places=2,
                                        null=False, default=0)
    member_discount = models.DecimalField(max_digits=6, decimal_places=2,
                                          null=False, default=0)
    order_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, default=0)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, default=0)
    original_cart = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(max_length=254, null=False,
                                  blank=False, default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number
        using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = self.lineitems.aggregate(
            Sum('lineitem_total'))['lineitem_total__sum'] or 0
        if self.order_total > 100:
            self.delivery_cost = 5
        else:
            self.delivery_cost = (
                self.order_total * settings.DELIVERY_CHARGE / 100)

        self.member_discount = (
            self.order_total * settings.MEMBER_DISCOUNT / 100)

        if self.user_profile:
            self.grand_total = self.order_total - self.member_discount + (
                self.delivery_cost)
        else:
            self.grand_total = self.order_total + self.delivery_cost

        print(str(self.user_profile) + " total: " + str(self.grand_total))

        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False,
                              on_delete=models.CASCADE,
                              related_name='lineitems')
    ticket = models.ForeignKey(Ticket, null=False,
                               blank=False,
                               on_delete=models.CASCADE)
    day = models.CharField(max_length=1, null=True, blank=True)
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2,
                                         null=False, blank=False,
                                         editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.ticket.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.ticket.friendly_name} on\
        order {self.order.order_number}'

tours/forms.py
from django import forms
from .models import Tour, Ticket, Match, Stadium, Gametype


class MatchForm(forms.ModelForm):

    class Meta:
        model = Match
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        tours = Tour.objects.all()
        friendly_names = [(t.id, t.get_friendly_name()) for t in tours]
        self.fields['tour'].choices = friendly_names


class TicketForm(forms.ModelForm):

    class Meta:
        model = Ticket
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class StadiumForm(forms.ModelForm):

    class Meta:
        model = Stadium
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class TourForm(forms.ModelForm):

    class Meta:
        model = Tour
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

tours/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .models import Tour, Match, Stadium, Ticket, Gametype
from .forms import MatchForm, TicketForm, StadiumForm, TourForm
# Create your views here.


def tours(request):
    """ A view to return the tours page, including sorting queries """

    tours = Tour.objects.all()
    matches = Match.objects.all()
    gametypes = Gametype.objects.all()
    stadiums = Stadium.objects.all()

    query = None
    stadium = None

    if request.GET:
        if 'tour' in request.GET:
            all_tours = Tour.objects.all()
            tour = request.GET['tour']
            tours = all_tours.filter(name=tour)

    context = {
        'tours': tours,
        'matches': matches,
        'gametypes': gametypes,
        'stadiums': stadiums,
        'search_term': query
    }

    return render(request, 'tours/tours.html', context)


def tickets(request, match_id):
    """
    A view to return the tickets page, showing the
    stadium and tickets available
    """

    match = get_object_or_404(Match, pk=match_id)
    stadiums = Stadium.objects.all()
    tickets = Ticket.objects.all()
    tours = Tour.objects.all()

    context = {
        'match': match,
        'stadiums': stadiums,
        'tickets': tickets,
        'tours': tours
    }

    return render(request, 'tours/tickets.html', context)


@login_required
def product_management(request):
    """ A view to return the index page """
    if not request.user.is_superuser:
        messages.error(
            request, 'Sorry, only store owners can access this page.')
        return redirect(reverse('tours'))

    tours = Tour.objects.all()

    if request.GET:
        if 'tour' in request.GET:
            all_tours = Tour.objects.all()
            tour = request.GET['tour']
            tours = all_tours.filter(name=tour)

    context = {
        'tours': tours
    }

    return render(request, 'tours/product_management.html', context)


@login_required
def add_match(request):
    """Add a match to the store"""
    if not request.user.is_superuser:
        messages.error(
            request, 'Sorry, only store owners can access this page.')
        return redirect(reverse('tours'))

    if request.method == "POST":
        form = MatchForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully added match!')
            return redirect(reverse('tours'))
        else:
            messages.error(
                request, 'Failed to add match. \
                Please ensure the form is valid.')
    else:
        form = MatchForm()

    tours = Tour.objects.all()

    if request.GET:
        if 'tour' in request.GET:
            all_tours = Tour.objects.all()
            tour = request.GET['tour']
            tours = all_tours.filter(name=tour)

    template = 'tours/add_match.html'
    context = {
        'form': form,
        'tours': tours

    }
    return render(request, template, context)


@login_required
def add_ticket(request):
    """Add a ticket to the store"""
    if not request.user.is_superuser:
        messages.error(
            request, 'Sorry, only store owners can access this page.')
        return redirect(reverse('tours'))

    if request.method == "POST":
        form = TicketForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully added ticket!')
            return redirect(reverse('add_ticket'))
        else:
            messages.error(
                request, 'Failed to add ticket. \
                Please ensure the form is valid.')
    else:
        form = TicketForm()

    template = 'tours/add_ticket.html'

    tours = Tour.objects.all()

    if request.GET:
        if 'tour' in request.GET:
            all_tours = Tour.objects.all()
            tour = request.GET['tour']
            tours = all_tours.filter(name=tour)

    context = {
        'form': form,
        'tours': tours

    }
    return render(request, template, context)


@login_required
def add_stadium(request):
    """Add a stadium to the store"""
    if not request.user.is_superuser:
        messages.error(
            request, 'Sorry, only store owners can access this page.')
        return redirect(reverse('tours'))

    if request.method == "POST":
        form = StadiumForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully added stadium!')
            return redirect(reverse('add_stadium'))
        else:
            messages.error(request, 'Failed to add stadium.\
            Please ensure the form is valid.')
    else:
        form = StadiumForm()

    tours = Tour.objects.all()

    if request.GET:
        if 'tour' in request.GET:
            all_tours = Tour.objects.all()
            tour = request.GET['tour']
            tours = all_tours.filter(name=tour)

    template = 'tours/add_stadium.html'
    context = {
        'form': form,
        'tours': tours

    }
    return render(request, template, context)


@login_required
def add_tour(request):
    """Add a tour to the store"""
    if not request.user.is_superuser:
        messages.error(
            request, 'Sorry, only store owners can access this page.')
        return redirect(reverse('tours'))

    if request.method == "POST":
        form = TourForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully added tour!')
            return redirect(reverse('add_tour'))
        else:
            messages.error(
                request, 'Failed to add tour. \
                Please ensure the form is valid.')
    else:
        form = TourForm()

    tours = Tour.objects.all()

    if request.GET:
        if 'tour' in request.GET:
            all_tours = Tour.objects.all()
            tour = request.GET['tour']
            tours = all_tours.filter(name=tour)

    template = 'tours/add_tour.html'
    context = {
        'form': form,
        'tours': tours

    }
    return render(request, template, context)


@login_required
def edit_match(request, match_id):
    """edit a match in the store"""
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, \
        only store owners can access this page.')
        return redirect(reverse('tours'))

    match = get_object_or_404(Match, pk=match_id)
    if request.method == 'POST':
        form = MatchForm(request.POST, request.FILES, instance=match)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated match!')
            return redirect(reverse('product_management'))
        else:
            messages.error(request, 'Failed to \
            update match. Please ensure the form is valid.')
    else:
        form = MatchForm(instance=match)
        messages.info(request, f'You are editing {match.name}')

    tours = Tour.objects.all()

    if request.GET:
        if 'tour' in request.GET:
            all_tours = Tour.objects.all()
            tour = request.GET['tour']
            tours = all_tours.filter(name=tour)

    template = 'tours/edit_match.html'
    context = {
        'form': form,
        'match': match,
        'tours': tours
    }
    return render(request, template, context)


@login_required
def edit_ticket(request, ticket_id):
    """edit a ticket in the store"""
    if not request.user.is_superuser:
        messages.error(
            request, 'Sorry, only store owners can access this page.')
        return redirect(reverse('tours'))

    ticket = get_object_or_404(Ticket, pk=ticket_id)
    if request.method == 'POST':
        form = TicketForm(request.POST, request.FILES, instance=ticket)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated ticket!')
            return redirect(reverse('product_management'))
        else:
            messages.error(
                request, 'Failed to update ticket.\
                Please ensure the form is valid.')
    else:
        form = TicketForm(instance=ticket)
        messages.info(request, f'You are editing {ticket.friendly_name}')

    tours = Tour.objects.all()

    if request.GET:
        if 'tour' in request.GET:
            all_tours = Tour.objects.all()
            tour = request.GET['tour']
            tours = all_tours.filter(name=tour)

    template = 'tours/edit_ticket.html'
    context = {
        'form': form,
        'ticket': ticket,
        'tours': tours
    }
    return render(request, template, context)


@login_required
def delete_match(request, match_id):
    """Delete a match from the store"""
    if not request.user.is_superuser:
        messages.error(
            request, 'Sorry, only store owners can access this page.')
        return redirect(reverse('tours'))

    match = get_object_or_404(Match, pk=match_id)
    match.delete()
    messages.success(request, "Match deleted!")
    return redirect(reverse('tours'))


@login_required
def delete_ticket(request, ticket_id):
    """Delete a match from the store"""
    if not request.user.is_superuser:
        messages.error(
            request, 'Sorry, only store owners can access this page.')
        return redirect(reverse('tours'))

    ticket = get_object_or_404(Ticket, pk=ticket_id)
    ticket.delete()
    messages.success(request, "Ticket deleted!")
    return redirect(reverse('product_management'))

tours/templates/tours/add_match.html
{% extends "base.html" %}
{% load static %}
{% block page_header %}
{% endblock %}
{% block content %}
<div class="container">
   <div class="row">
      <div class="col m6 offset-m3 center product-management ">
         <h2>Product Management</h2>
         <h5>Add a Match</h5>
      </div>
   </div>
   <div class="row">
      <div class="col m6 offset-m3  center">
         <form method="POST" action="{% url 'add_match' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <a href="{% url 'product_management' %}" class="btn btn-white">Cancel</a>
            <button class="btn btn-blue" type="submit">Add Match</button>
         </form>
      </div>
   </div>
</div>
</div>
{% endblock %}

tours/templates/tours/add_stadium.html
{% extends "base.html" %}
{% load static %}
{% block page_header %}
{% endblock %}
{% block content %}
<div class="container">
   <div class="row">
      <div class="col m6 offset-m3  center product-management">
         <h2>Product Management</h2>
         <h5>Add a Stadium</h5>
      </div>
   </div>
   <div class="row">
      <div class="col m6 offset-m3  center">
         <form method="POST" action="{% url 'add_stadium' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <a href="{% url 'product_management' %}" class="btn btn-white">Cancel</a>
            <button class="btn btn-blue" type="submit">Add Stadium</button>
         </form>
      </div>
   </div>
</div>
{% endblock %}

tours/templates/tours/add_ticket.html
{% extends "base.html" %}
{% load static %}
{% block page_header %}
{% endblock %}
{% block content %}
<div class="container">
   <div class="row">
      <div class="col m6 offset-m3 center product-management ">
         <h2>Product Management</h2>
         <h5>Add a Ticket</h5>
      </div>
   </div>
   <div class="row">
      <div class="col m6 offset-m3 center">
         <form method="POST" action="{% url 'add_ticket' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <a href="{% url 'product_management' %}" class="btn btn-white">Cancel</a>
            <button class="btn btn-blue" type="submit">Add Ticket</button>
         </form>
      </div>
   </div>
</div>
</div>
{% endblock %}

tours/templates/tours/add_tour.html
{% extends "base.html" %}
{% load static %}
{% block page_header %}
{% endblock %}
{% block content %}
<div class="container">
   <div class="row">
      <div class="col m6 offset-m3  center product-management ">
         <h2>Product Management</h2>
         <h5>Add a Tour</h5>
      </div>
   </div>
   <div class="row">
      <div class="col m6 offset-m3  center">
         <form method="POST" action="{% url 'add_tour' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <a href="{% url 'product_management' %}" class="btn btn-white">Cancel</a>
            <button class="btn btn-blue" type="submit">Add Tour</button>
         </form>
      </div>
   </div>
</div>
{% endblock %}

tours/templates/tours/edit_match.html
{% extends "base.html" %}
{% load static %}
{% block page_header %}
{% endblock %}
{% block content %}
<div class="container">
   <div class="row">
      <div class="col m6 offset-m3  center product-management ">
         <h2>Product Management</h2>
         <h5>Edit a Match</h5>
      </div>
   </div>
   <div class="row">
      <div class="col m6 offset-m3  center">
         <form method="POST" action="{% url 'edit_match' match.id %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <a href="{% url 'tours' %}" class="btn btn-white">Cancel</a>
            <button class="btn btn-blue" type="submit">Update Match</button>
         </form>
      </div>
   </div>
</div>
</div>
{% endblock %}

tours/templates/tours/edit_ticket.html
{% extends "base.html" %}
{% load static %}
{% block page_header %}
{% endblock %}
{% block content %}
<div class="container">
   <div class="row">
      <div class="col m6 offset-m3 center product-management ">
         <h2>Product Management</h2>
         <h5>Edit a Ticket</h5>
      </div>
   </div>
   <div class="row">
      <div class="col m6 offset-m3  center">
         <form method="POST" action="{% url 'edit_ticket' ticket.id %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <a href="{% url 'tours' %}" class="btn btn-white">Cancel</a>
            <button class="btn btn-blue" type="submit">Update Ticket</button>
         </form>
      </div>
   </div>
</div>
</div>
{% endblock %}

tours/templates/tours/product_management.html
{% extends "base.html" %}
{% load static %}
{% block page_header %}
{% endblock %}
{% block content %}
<div class="container">
   <div class="row">
      <div class="col m6 offset-m3  center product-management ">
         <h2>Product Management</h2>
      </div>
   </div>
   <div class="row">
      <div class="col s12 m6 center">
         <div class="card">
            <div class="card-image">
               <img src="{{MEDIA_URL}}images/afridi.jpg" alt="Afridi">          
            </div>
            <div class="card-action">
               <a href="{% url 'add_match' %}" class="btn btn-blue">Add Match</a>
            </div>
         </div>
      </div>
      <div class="col s12 m6 center">
         <div class="card">
            <div class="card-image">
               <img src="{{MEDIA_URL}}images/kohli.jpg" alt="Kohli">          
            </div>
            <div class="card-action">
               <a href="{% url 'add_ticket' %}" class="btn btn-blue">Add Ticket</a>
            </div>
         </div>
      </div>
      <div class="col s12 m6 center">
         <div class="card">
            <div class="card-image">
               <img src="{{MEDIA_URL}}images/edgbaston.jpg" alt="Edgbaston">          
            </div>
            <div class="card-action">
               <a href="{% url 'add_stadium' %}" class="btn btn-blue">Add Stadium</a>
            </div>
         </div>
      </div>
      <div class="col s12 m6 center">
         <div class="card">
            <div class="card-image">
               <img src="{{MEDIA_URL}}images/mo.jpg" alt="Mo Ali">          
            </div>
            <div class="card-action">
               <a href="{% url 'add_tour' %}" class="btn btn-blue">Add Tour</a>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock %}

tours/templates/tours/tickets.html
{% extends "base.html" %}
{% load static %}
{% block page_header %}
{% endblock %}
{% block content %}
<div class="container-fluid">
   <div class="row center-align info-row">
      <h3>{{match.tour.friendly_name}}: {{match.name}}</h3>
      {% for stadium in stadiums%}
      {% if match.stadium == stadium %}
      <h4>{{stadium.full_name}}</h4>
      <h5>{{match.date}}</h5>
      <div class="col m6">       
         <a href="{{stadium.image_url}}" target="_blank"><img src="{{stadium.image_url}}" alt="{{stadium.name}}" style="max-width: 100%;"></a>
         {% endif %}
         {% endfor %}          
      </div>
      <div class="col m6 center form-options">
         {% for ticket in tickets %}
         {% if match == ticket.match %}
         <h5>{{ ticket.friendly_name }}: £{{ticket.price}}</h5>
         <form action="{% url 'add_to_cart' ticket.id %}" method="POST" >
            {% csrf_token %}
            {% if match.gametype.name == "Test Match" %}
            <select name="day" required data-item_id="{{ticket.id}}" id="id_day">
               <option value="" disabled selected>Choose Day</option>
               <option value="1" class="white-text">Day 1</option>
               <option value="2">Day 2</option>
               <option value="3">Day 3</option>
               <option value="4">Day 4</option>
            </select>
            <label>Choose Day</label>  
            {% endif %}
            Quantity:
            <input class="qty_input white-text center" type="number" name="quantity" value="1" min="1" max="4"
               data-item_id="{{ ticket.id1 }}" id="id_qty_{{ ticket.id }}" style="max-width: 150px;"><br>
            <a href="{% url 'tours'%}" class="btn btn-white"><i class="fas fa-chevron-left"></i> Back to Tours</a>
            <input type="submit" class="btn btn-white" value="Buy Tickets">
            <input type="hidden" name="redirect_url" value="{{request.path}}">
         </form>
         {% if request.user.is_superuser %}
         <a href="{% url 'edit_ticket' ticket.id %}" class="btn btn-white">Edit Ticket</a>
         <a href="{% url 'delete_ticket' ticket.id %}" class="btn btn-white">Delete Ticket</a> 
         {% endif %} 
         {% endif %}  
         {% endfor %}
      </div>
   </div>
</div>
{% endblock %}

tours/templates/tours/tours.html
{% extends "base.html" %}
{% load static %}
{% block page_header %}
{% endblock %}
{% block content %}
<div class="container-fluid">
   <div class="row">
      <div class="col6 center-align tour-header">
         <h2>Tours</h2>
      </div>
   </div>
   <div class="row">
      <div class="col m4 offset-m4 center-align tour-filter">
         <!-- Dropdown Trigger -->
         <a class="dropdown-trigger btn btn-white" href="#" data-target="dropdown3" style="padding: 2px;">
         Filter
         </a>
         <!-- Dropdown Structure -->
         <ul id="dropdown3" class="dropdown-content">
            {% for tour in tours %}
            <li><a href="{% url 'tours' %}?tour={{tour.name}}">{{tour.friendly_name}}</a></li>
            <li class="divider" tabindex="-1"></li>
            {% endfor %}                    
         </ul>
         <a href="{% url 'tours' %}" class="btn btn-white">Reset</a>     
      </div>
   </div>
   {% for tour in tours %}
   <div class="row center-align tour-row" style="background-image: url('{{tour.image_url}}'); background-size: cover;
      -webkit-background-size: cover;	-moz-background-size: cover;	-o-background-size: cover;
      background-repeat: no-repeat;	background-position: 50% 50%; min-height: 70vh; margin-bottom: 0;">
      <h3>{{tour.friendly_name}}</h3>
      <div class="col m6 offset-m6 center-align tour-details" data-aos="fade-up">
         {% for match in matches %}
         {% if match.tour == tour%}
         <p>{{match.name}}, {{match.stadium.full_name}}:<br> {{match.date}}</p>
         <a href="{% url 'tickets' match.id %}" class="btn btn-blue" >Buy tickets</a>
         {% if request.user.is_superuser %}
         <a href="{% url 'edit_match' match.id %}" class="btn btn-white" >Edit match</a>
         <a href="{% url 'delete_match' match.id %}" class="btn btn-blue" >Delete match</a>
         {% endif %}
         {% endif %}
         {% endfor %}
      </div>
   </div>
   {% endfor %}
</div>
<div class="btt-button">
   <a href="" class="btn btn-blue btt-link">Back to Top</a>
</div>
{% endblock %}
{% block postloadjs %}
{{block.super}}
<script>
   $(.btt-link).click(function(e){
       window.scrollTo(0,0)
   })
</script>
<!-- AOS Script -->
<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
<script>
   AOS.init();
</script>
{{endblock}}
{% endblock %}